runtime: python39  # Specify the appropriate Python version (e.g., python38, python39)
entrypoint: bash -c "python audiobackend.py & streamlit run audiofrontend.py --server.port $PORT"  # Adjust 'main:app' to your own application structure.

handlers:
  - url: /.*
    script: auto

env_variables:
  EXAMPLE_ENV_VAR: 'value'
